# change this file to be named .secrets.yaml
auth:
  panorama:
    username: "this-is-just-a-placeholder"
    password: "this-is-just-a-placeholder"
  firewall:
    username: "this-is-just-a-placeholder"
    password: "this-is-just-a-placeholder"
