name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers workflow on version tags, e.g., v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
          - os: windows-latest
            goos: windows
            goarch: amd64
          - os: macos-latest
            goos: darwin
            goarch: amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: '1.20'

      # Initialize Go Module (since go.mod is not checked in)
      - name: Initialize Go Module
        run: go mod init github.com/cdot65/pan-os-cdss-certificate-registration

      # Tidy up dependencies
      - name: Tidy Go Module
        run: go mod tidy

      - name: Build Binary
        run: |
          echo "Building for ${{ matrix.goos }}/${{ matrix.goarch }}"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o cdss-cert-register-${{ matrix.goos }}-${{ matrix.goarch }} ./main.go

      - name: Archive Binary
        run: |
          zip cdss-cert-register-${{ matrix.goos }}-${{ matrix.goarch }}.zip cdss-cert-register-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cdss-cert-register-${{ matrix.goos }}-${{ matrix.goarch }}
          path: cdss-cert-register-${{ matrix.goos }}-${{ matrix.goarch }}.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cdss-cert-register-linux-amd64.zip
            cdss-cert-register-windows-amd64.zip
            cdss-cert-register-darwin-amd64.zip
            cdss-cert-register-darwin-arm64.zip
          token: ${{ secrets.GH_SECRET }}