name: Build and Test Pull Request

on:
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: '1.21.x'

      # Initialize Go Module
      - name: Initialize Go Module
        run: go mod init github.com/cdot65/pan-os-cdss-certificate-registration

      # Clear module cache
      - name: Clear module cache
        run: go clean -modcache

      # Tidy up dependencies
      - name: Tidy Go Module
        run: go mod tidy

      # Build the binary
      - name: Build Binary
        run: |
          go build -v ./main.go

      # Run tests on all files with *_test.go in name
      - name: Run Tests
        run: |
          go test -v ./...