name: Build and Test Pull Request

on:
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: '1.20'

      # Initialize Go Module
      - name: Initialize Go Module
        run: go mod init github.com/cdot65/pan-os-cdss-certificate-registration

      # Tidy up dependencies
      - name: Tidy Go Module
        run: go mod tidy

      # Build the binary
      - name: Build Binary
        run: |
          go build -v ./main.go

      # Run tests on main.go
      - name: Run Main Tests
        run: |
          go test -v main.go

      # Run tests on config/config.go
      - name: Run Config Tests
        run: |
          go test -v config/config.go

      # Run tests on devices/devices.go
      - name: Run Devices Tests
        run: |
          go test -v devices/devices.go

      # Run tests on logger/logger.go
      - name: Run Logger Tests
        run: |
          go test -v logger/logger.go